CREATE TABLE IF NOT EXISTS users(
    id_user BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(150) NOT NULL,
    email VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS pulls(
    id_pull BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_user BIGINT UNSIGNED NOT NULL,
    name_pull VARCHAR(150) NOT NULL,
    FOREIGN KEY (id_user) REFERENCES users(id_user) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS questions(
    id_question BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_pull BIGINT UNSIGNED NOT NULL,
    id_user BIGINT UNSIGNED NOT NULL,
    title_question VARCHAR(150) NOT NULL,
    description_question VARCHAR(250) NULL,
    type_question INT NOT NULL DEFAULT 0,
    FOREIGN KEY (id_pull) REFERENCES pulls(id_pull) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_user) REFERENCES users(id_user) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS answers(
    id_answer BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_question BIGINT UNSIGNED NOT NULL,
    name_answer VARCHAR(250) NOT NULL,
    FOREIGN KEY (id_question) REFERENCES questions(id_question) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS rooms(
    id_room BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_pull BIGINT UNSIGNED NOT NULL,
    id_user BIGINT UNSIGNED NOT NULL,
    pin INT(4) NOT NULL UNIQUE,
    status TINYINT NOT NULL DEFAULT 1,
    FOREIGN KEY (id_pull) REFERENCES pulls(id_pull) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_user) REFERENCES users(id_user) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS players(
    id_player BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_room BIGINT UNSIGNED NOT NULL,
    username VARCHAR(50) NOT NULL,
    FOREIGN KEY (id_room) REFERENCES rooms(id_room) ON UPDATE CASCADE ON DELETE CASCADE
);
